#!/usr/bin/env python3
import sys, subprocess

XIAOMI_DEVICE = "192.168.178.154:43199"

def main():
    if len(sys.argv) < 2:
        print("User-Fehler: Gib einen Befehl für das Xiaomi mit! (z.B.: xcmd ps)")
        sys.exit(1)
        
    cmd = sys.argv[1:]
    
    # Check, ob der Befehl ein interner Alias ist
    if cmd[0] == "apps":
        adb_cmd = ["adb", "-s", XIAOMI_DEVICE, "shell", "pm", "list", "packages", "-3"]
    elif cmd[0] == "reboot":
        adb_cmd = ["adb", "-s", XIAOMI_DEVICE, "reboot"]
    elif cmd[0] == "battery":
        adb_cmd = ["adb", "-s", XIAOMI_DEVICE, "shell", "dumpsys", "battery"]
    else:
        # Normaler adb shell Befehl
        adb_cmd = ["adb", "-s", XIAOMI_DEVICE, "shell"] + cmd

    res = subprocess.run(adb_cmd, capture_output=True, text=True)
    if res.stdout:
        print(res.stdout.strip())
    if res.stderr:
        print(f"[ERR] {res.stderr.strip()}")

if __name__ == "__main__":
    main()
